### ISSUE TITLE
Error Sorting With ExpandoObject

### ISSUE THREAD

**Issue by Jorgo78** [telerik/blazor-ui#147]
Good evening,
i can't understand why table sorting doesn't work with expandoobject. I get the error "Failed to compare two elements in the array"

System.ArgumentException: At least one object must implement IComparable

Blazor WebAssembly .net 6

Best Regards

**Comment by marin-bratanov** [comment]
Sorting works for me with this sample project https://github.com/telerik/blazor-ui/tree/master/grid/binding-to-expando-object

Another dynamic data structure could be a data table and sorting works there too: https://demos.telerik.com/blazor-ui/grid/data-table

If comparing against these samples does not help you move forward, I recommend opening a support ticket for the concrete situation. The Issues section for this repo is for issues with the examples in it, rather than questions about the functionality of the components. For that, tickets or the forums are a better place: https://docs.telerik.com/blazor-ui/introduction#support-options
