### ISSUE TITLE
"StateHasChanged" in Event Handlers

### ISSUE THREAD

**Issue by BenHayat** [telerik/blazor-ui#21]
Hello Team;

I noticed in the Blazor docs that said:

> Event handlers can also be asynchronous and return a Task. **There's no need to manually call** StateHasChanged(). Exceptions are logged when they occur.

Which according to another statement somewhere in the forum I read that the EventHandler does an "Implicit" call to to StateHasChanged() method.

In your demos, I see that still being called in the event handlers. I commented out a few (like in grid samples) and everything worked.
I thought I share this new change with the team.

Thanks!
..Ben

**Comment by ivanchev** [comment]
Some of these statements might have been overlooked after the change to EventCallback a while back. Since there are still some issues with the event, we've not yet switched all internal event handler to it, and use Action<> at some places. This does not invoke StateHasChanged. 

We will cleanup the demos application to get rid of any unneeded usages of StateHasChanged, but since the site is no longer public, I'm marking this as closed.

Thank you for reporting this.
