### ISSUE TITLE
adjust-height-with-browser demo using 3rd party library when functionality is built in

### ISSUE THREAD

**Issue by ASLAnthony** [telerik/blazor-ui#311]
The Demo adjust-height-with-browser uses the 3rd party library BlazorPro.BlazorSize.

According to the library's GitHub page, it states, "If you’re already a Telerik customer, there’s no need to use BlazorSize; instead, you may use the TelerikMediaQuery component."

Given that installing and setting up the BlazorPro component involves additional requirements, why is the TelerikMediaQuery component not being used instead?

**Comment by dimodi** [comment]
Hi @ASLAnthony 

On one hand, this sample was created by a customer of ours before the MediaQuery component existed. On the other hand, the MediaQuery component is designed to fire events at explicitly defined thresholds and not continuously. The latter makes the MediaQuery component more suitable for width-related resizing and adjustments, rather than height-related ones.

It's also true that [the sample is partially obsolete and I just marked it as such](https://github.com/telerik/blazor-ui/blob/master/grid/adjust-height-with-browser/README.md). The up-to-date documentation resources are here:

* [Adjust Grid Height to Match the Browser Viewport Height](https://docs.telerik.com/blazor-ui/knowledge-base/grid-adjust-height-with-browser)
* [Scroll to Selected Grid Row](https://docs.telerik.com/blazor-ui/knowledge-base/grid-scroll-to-selected-row)
* [Apply Custom Grid Row or Cell Styles](https://docs.telerik.com/blazor-ui/knowledge-base/grid-conditional-cell-background)
* [Override the Telerik Theme](https://docs.telerik.com/blazor-ui/styling-and-themes/override-theme-styles)

There is one exception to the above information and it concerns the rare requirement to change the Grid `PageSize`, depending on the Grid height.
