### ISSUE TITLE
Can you please add authorization and authentication to this project? 

### ISSUE THREAD

**Issue by RaviTeja1309** [telerik/blazor-ui#59]
Everything looks good but unable to implement your profile page and login in page to built blazer identity 

### Bug report

**For Support request - Please do not submit support request here, instead see the** [Telerik UI for Blazor forums](https://www.telerik.com/forums/blazor) or our [support system](http://www.telerik.com/support) **at Telerik.com** !

**For Feature Requests - please submit those into [our feedback portal](https://www.telerik.com/support/feedback)**

### Reproduction of the problem
_(bug report only)_
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem by referencing a sample project.

### Current behavior
_(optional)_
Provide additional information if the steps for reproducing the faulty behavior are not sufficient to describe the issue.

### Expected/desired behavior
Explain what the expected behavior of the functionality is

### Environment

* **Telerik UI for Blazor version:** x.y.z
* **Browser:** [all | Chrome XX | Firefox XX | Edge XX]
* **App Type** [server | client]

**Comment by marin-bratanov** [comment]
Hello @RaviTeja1309 

I can suggest you start reviewing how authorization and authentication work in Blazor from the following MSDN page: [https://docs.microsoft.com/en-us/aspnet/core/blazor/security/?view=aspnetcore-5.0](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/?view=aspnetcore-5.0). This should let you build a project (maybe by using the MS Templates) that already has the desired identity provider, so you can then start copying examples for our components into it.

Generally, authentication and identity are highly specific to each application, which is why we do not implement them in sample apps (moreover, they make the apps clunky and difficult to use, while their main purpose is to showcase our components, not framework features per se). Thus, we cannot add such functionality to any of the projects in this repo.
